services:
  cert:
    image: xdocker_cert
    volumes:
      - letsencrypt:/etc/letsencrypt
      - openssl:/etc/ssl
    tty: true
    stdin_open: true
    ports:
      - "7080:80/tcp"

volumes:
  letsencrypt:
  openssl:

