services:
  cert:
    image: xdocker_cert
    volumes:
      - letsencrypt:/etc/letsencrypt
      - selfca:/usr/local/etc/ca
    tty: true
    stdin_open: true
    ports:
      - "7080:80/tcp"

volumes:
  letsencrypt:
  selfca:
